### ISSUE TITLE
Release rails 5.1 compatibility

### ISSUE THREAD

**Issue by d1ceward** [dongli/upload-image#2]
Hello,
Please can you release to RubyGems changes made by #1 to avoid using :
`gem 'upload-image', github: 'dongli/upload-image', ref: 'd6b6cb9'`

**Comment by dongli** [comment]
@D1ceWard Hi, thanks for your attention! I have already switched to other works (not rails). If you find this work useful, you can folk it and release a RubyGem~ Cheers!
